package routes

import (
	_ "../docs" // docs is generated by Swag CLI, you have to import it.
	"../handler"
	"../middleware"
	"../user"
	"github.com/gorilla/mux"
	"github.com/jinzhu/gorm"
	httpSwagger "github.com/swaggo/http-swagger"
	"net/http"
)

func InitRoute(db *gorm.DB) *mux.Router {

	r := mux.NewRouter().StrictSlash(true)

	// swagger
	r.PathPrefix("/swagger/").Handler(httpSwagger.Handler(
		httpSwagger.URL("http://localhost:3000/swagger/doc.json"), //The url pointing to API definition
	))

	api := r.PathPrefix("/v1").Subrouter()
	api.Use(middleware.CorsEveryWhere)
	api .Use(middleware.Authentication)
	api.Use(middleware.RequestLogger)

	userRepo := user.NewUserRepository(db)
	// auth
	authHandler := handler.NewAuthHandler(userRepo)
	api.HandleFunc("/auth/login", authHandler.HandleLogin).Methods(http.MethodPost, http.MethodOptions)

	// user
	userHandler := handler.NewUserHandler(userRepo)
	api.HandleFunc("/users", userHandler.HandleGetAll).Methods(http.MethodGet)
	api.HandleFunc("/users", userHandler.HandleStore).Methods(http.MethodPost, http.MethodOptions)
	api.HandleFunc("/users/{id}", userHandler.HandleGetByID).Methods(http.MethodGet)
	api.HandleFunc("/users/{id}", userHandler.HandleUpdate).Methods(http.MethodPut, http.MethodOptions)
	api.HandleFunc("/users/{id}/change-password", userHandler.HandleChangePassword).Methods(http.MethodPut, http.MethodOptions)

	return r
}
